import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'on-tertiary-fixed-variant': '#004f51',
                'inverse-primary': '#a0401f',
                tertiary: '#67d7da',
                surface: '#1b110e',
                'tertiary-fixed-dim': '#67d7da',
                'surface-tint': '#ffb59e',
                'outline-variant': '#56423c',
                'tertiary-container': '#1da0a3',
                'surface-variant': '#3e322f',
                'primary-fixed-dim': '#ffb59e',
                'inverse-on-surface': '#3a2e2a',
                'on-secondary-fixed-variant': '#3c4b37',
                'on-error': '#690005',
                'on-primary-container': '#521300',
                'secondary-fixed': '#d7e8cd',
                'on-error-container': '#ffdad6',
                'surface-container-highest': '#3e322f',
                error: '#ffb4ab',
                background: '#1b110e',
                'surface-container-lowest': '#150c09',
                'surface-dim': '#1b110e',
                'on-surface': '#f2ded9',
                secondary: '#bbcbb1',
                'primary-container': '#e1704b',
                'surface-container': '#281d1a',
                'on-tertiary-fixed': '#002021',
                'tertiary-fixed': '#85f4f7',
                'on-secondary-container': '#aabaa1',
                'surface-container-high': '#332724',
                'primary-fixed': '#ffdbd0',
                'secondary-fixed-dim': '#bbcbb1',
                'secondary-container': '#3c4b37',
                'on-secondary': '#263422',
                'surface-container-low': '#231916',
                'on-surface-variant': '#ddc0b8',
                'error-container': '#93000a',
                'on-tertiary-container': '#002f30',
                'on-primary': '#5e1700',
                'surface-bright': '#433633',
                'on-primary-fixed': '#3a0b00',
                outline: '#a58b84',
                'on-secondary-fixed': '#121f0e',
                primary: '#ffb59e',
                'inverse-surface': '#f2ded9',
                'on-tertiary': '#003738',
                'on-background': '#f2ded9',
                'on-primary-fixed-variant': '#802909',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                gutter: '24px',
                'container-max': '1280px',
                'margin-desktop': '64px',
                'margin-mobile': '20px',
                unit: '8px',
            },
            fontFamily: {
                sans: ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
                display: ['EB Garamond', 'serif'],
                'display-lg': ['EB Garamond', 'serif'],
                'headline-lg': ['EB Garamond', 'serif'],
                'headline-md': ['EB Garamond', 'serif'],
                'headline-lg-mobile': ['EB Garamond', 'serif'],
                body: ['Hanken Grotesk', 'sans-serif'],
                'body-md': ['Hanken Grotesk', 'sans-serif'],
                'body-lg': ['Hanken Grotesk', 'sans-serif'],
                'label-md': ['Hanken Grotesk', 'sans-serif'],
            },
            fontSize: {
                'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
                'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
                'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
                'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
            },
            keyframes: {
                fadeUp: {
                    from: { opacity: '0', transform: 'translateY(2rem)' },
                    to: { opacity: '1', transform: 'translateY(0)' },
                },
            },
            animation: {
                fadeUp: 'fadeUp 1s ease-out forwards',
            },
        },
    },

    plugins: [forms],
};
